imports:
    - { resource: config.yml }


#doctrine:
#    dbal:
#        options:
#            MYSQL_ATTR_SSL_CA : '%env(doctrn_ca)%'
#            MYSQL_ATTR_SSL_KEY : '%env(doctrn_private_key)%'
#            MYSQL_ATTR_SSL_CERT : '%env(doctrn_certificate)%'



monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: error_log
            #type: stream
            #path: 'php://stderr'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
